package bc.BuildingControl.guis;

import bc.BuildingControl.exts.TempSensorNative_GUI;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import java.awt.*;

public class TempSensorGui {
    private JPanel pnlTempSensor;
    private JSpinner spnTemperature;

    public TempSensorGui() {
        spnTemperature.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                float v = Float.parseFloat(spnTemperature.getValue().toString());
                TempSensorNative_GUI.setTemperature(v);
            }
        });
    }

    public TempSensorGui(float initialTemp, float lowSetPoint, float highSetPoint) {
        this();

        this.spnTemperature.setModel(new SpinnerNumberModel(initialTemp, lowSetPoint, highSetPoint, 1));
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pnlTempSensor = new JPanel();
        pnlTempSensor.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Sensed Temperature");
        pnlTempSensor.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        spnTemperature = new JSpinner();
        pnlTempSensor.add(spnTemperature, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlTempSensor;
    }

}
