package bc.BuildingControl.guis;

import bc.BuildingControl.FanAck;
import bc.BuildingControl.exts.FanGUI_Ext;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Vector;

public class FanGui {
    public JPanel pnlFan;
    private JComboBox<FanAck.Type> cmbFanAck;

    public FanGui() {
        cmbFanAck.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                FanGUI_Ext.setFanAck(cmbFanAck.getItemAt(cmbFanAck.getSelectedIndex()));
            }
        });
    }

    public FanGui(Vector<FanAck.Type> values) {
        this();

        cmbFanAck.setModel(new DefaultComboBoxModel<>(values));
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pnlFan = new JPanel();
        pnlFan.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        pnlFan.setBorder(BorderFactory.createTitledBorder(null, "Fan Sensor", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final JLabel label1 = new JLabel();
        label1.setText("Fan Acknowledgment");
        pnlFan.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cmbFanAck = new JComboBox();
        pnlFan.add(cmbFanAck, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlFan;
    }

}
